### ISSUE TITLE
Improve reporting of triples failing validation

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#8]
The pipeline building the robot template emits a warning when it encounters a relationship that doesn't validate against the uberongraph triplestore.  This is rather ugly - it just uses a stringified version of the input row.  Code here:

https://github.com/obophenotype/CCF_tools/blob/master/src/template_generation_tools.py#L32

This should instead emit a compact message to a log => a useable report on non validated triples to follow up on.

**Comment by dosumis** [comment]
Example of current output

```
/Users/davidos/Documents/GitHub/CCF_tools/src/template_generation_tools.py:32: UserWarning: Not adding s                    UBERON:0002302
slabel         myocardium of atrium
user_slabel              myocardium
o                    UBERON:0002079
olabel          left cardiac atrium
user_olabel             left atrium
Name: 18, dtype: object - relationship not valid in Uberon/CL
  warnings.warn("Not adding %s - relationship not valid in Uberon/CL" % str(r))
```

**Comment by dosumis** [comment]
Hot fix on master 7776c5b

**Comment by emquardokus** [comment]
@dosumis a description of what is checked by validation tool is needed since in some cases there are issues with lack of relationship in uberon/cl and in some cases inconsistent use between similar situations  Left vs Right in heart vs Left vs Right in lung are examples I've recently run into.  Since then I've made a note to double check whether these instances are all being flagged.  So for instance if anatomical structure that is part-of or located-in atrium (where L and R exist), it may show as part of atrium, but not as part of right or left atrium and then trips out in validation script.  On the other hand, I've seen it where for lung these same types of cases ARE listed as part of right or part of left lung.  Is there a way to deal with that type of thing easily?

**Comment by dosumis** [comment]
@emquardokus Lets just work back from the reports.
